spring.application.name=financebudgetapp

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/budget
spring.datasource.username=budget
spring.datasource.password=budget

# JPA
spring.jpa.hibernate.ddl-auto=validate

# Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
